# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Haru Jeon - Curating, Writing, and Art projects"
description: "Curating, Writing, and Art projects"
author:      "Haru Jeon"
